# Generated by Django 5.1.1 on 2024-10-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Cars', 'Cars'), ('Bikes', 'Bikes')], default='Cars', max_length=20)),
            ],
        ),
    ]
