# Generated by Django 5.0.6 on 2024-06-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='site/')),
                ('icon', models.ImageField(blank=True, upload_to='site/')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(default='Set Email', max_length=255)),
                ('address', models.CharField(default='Set Address', max_length=255)),
                ('facebook_url', models.URLField(default='www.facebook.com')),
                ('instagram_url', models.URLField(default='www.instagram.com')),
                ('x_url', models.URLField(default='www.x.com')),
            ],
        ),
    ]
