# Generated by Django 5.1.1 on 2024-10-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeRepairingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.ImageField(blank=True, upload_to='site/')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('services', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='MembershipServicesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('monthly', 'monthly'), ('year', 'year')], default='monthly', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
