# Generated by Django 5.1.1 on 2024-09-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='no_of_workers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
